name: build

on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: build win
        run: npm run build:app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pack/*.exe
            pack/*.exe.blockmap
            pack/latest.yml
            pack/hotVersion.json
            pack/renderer.zip
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
